// src/vue/components/PixelCanvas.vue
<template>
<div class="pixel-canvas-container">
    <div class="pixel-canvas border" @mouseover="onMouseOver" @mouseleave="onMouseLeave" :style="{gridTemplateColumns: `repeat(${axisSize}, 1fr)`, gridTemplateRows: `repeat(${axisSize}, 1fr)`}">
        <PixelCanvasCell v-for="pixel of pixels" :key="pixel.id" :pixel="pixel"/>
    </div>
</div>
</template>

<script>
import Vuex from "vuex";

import { coordinatesFromIndex } from "../../common/canvas";
import PixelCanvasCell from "./PixelCanvasCell";

export default {
    name: "PixelCanvas",
    components: {
        PixelCanvasCell,
    },
    data() {
        return {
            cursorPosition: undefined,
        };
    },
    computed: {
        axisSize() {
            return this.$store.state.current.axisSize;
        },
        pixels() {
            return this.$store.state.current.pixels;
        },
    },
    mounted() {
        document.addEventListener("mousedown", this.onMouseDown, false);
        document.addEventListener("mouseup", this.onMouseUp, false);
    },
    beforeDestroy() {
        document.removeEventListener("mousedown", this.onMouseDown, false);
        document.removeEventListener("mouseup", this.onMouseUp, false);
    },
    watch: {
        cursorPosition: function (newPos, oldPos) {
            if (!newPos) {
                return;
            }

            if (!oldPos) {
                this.$store.commit("setPixel", newPos);
                return;
            }

            this.$store.commit("drawLine", {
                from: oldPos,
                to: newPos,
            });
        },
    },
    methods: {
        onMouseDown(event) {
            this.isDrawing = true;
            this.setCursorPositionFromEventTarget(event);
        },
        onMouseUp(event) {
            this.isDrawing = false;
            this.cursorPosition = undefined;
        },
        onMouseOver(event) {
            if (this.isDrawing) {
                this.setCursorPositionFromEventTarget(event);
            }
        },
        onMouseLeave(event) {
            this.cursorPosition = undefined;
        },
        setCursorPositionFromEventTarget(event) {
            const target = event.target;

            if (!target.classList.contains("pixel-canvas-cell")) {
                return;
            }

            this.cursorPosition = coordinatesFromIndex(parseInt(target.dataset.id));
        },
    },
};
</script>

// src/react/containers/PixelCanvas.jsx
import React from "react";
import { connect } from "react-redux";

import { coordinatesFromIndex } from "../../common/canvas";
import { drawLine, setPixel } from "../actions";
import PixelCanvasCell from "../components/PixelCanvasCell";

class PixelCanvas extends React.PureComponent {
    state = {
        isDrawing: false,
        cursorPosition: undefined,
    };

    render() {
        const canvasStyle = {
            gridTemplateColumns: `repeat(${this.props.axisSize}, 1fr)`,
            gridTemplateRows: `repeat(${this.props.axisSize}, 1fr)`,
        };

        return (
            <div className="pixel-canvas-container">
                <div className="pixel-canvas border" style={canvasStyle} onMouseOver={this.onMouseOver} onMouseLeave={this.onMouseLeave}>
                    {this.props.pixels.map(pixel => (<PixelCanvasCell key={pixel.id} pixel={pixel} />))}
                </div>
            </div>
        );
    }

    componentWillMount() {
        document.addEventListener("mousedown", this.onMouseDown, false);
        document.addEventListener("mouseup", this.onMouseUp, false);
    }

    componentWillUnmount() {
        document.removeEventListener("mousedown", this.onMouseDown, false);
        document.removeEventListener("mouseup", this.onMouseUp, false);
    }

    onMouseDown = event => {
        this.setState({
            isDrawing: true,
        });
        this.setCursorPositionFromEventTarget(event);
    };

    onMouseUp = event => {
        this.setState({
            isDrawing: false,
            cursorPosition: undefined,
        });
    };

    onMouseOver = event => {
        if (this.state.isDrawing) {
            this.setCursorPositionFromEventTarget(event);
        }
    };

    onMouseLeave = event => {
        this.setState({
            cursorPosition: undefined,
        });
    };

    setCursorPositionFromEventTarget(event) {
        const target = event.target;

        if (!target.classList.contains("pixel-canvas-cell")) {
            return;
        }

        const oldPos = this.state.cursorPosition;
        const newPos = coordinatesFromIndex(parseInt(target.dataset.id));

        if (oldPos === newPos) {
            return;
        }

        if (oldPos) {
            this.props.drawLine(oldPos, newPos);
        } else {
            this.props.setPixel(newPos);
        }

        this.setState({
            cursorPosition: newPos,
        });
    }

    setCursorPosition(pos) {
        this.setState({
            cursorPosition: pos,
        });
    }
}

function mapStateToProps(state) {
    return {
        axisSize: state.current.axisSize,
        pixels: state.current.pixels,
    };
}

function mapDispatchToProps(dispatch) {
    return {
        setPixel(pos) {
            dispatch(setPixel(pos));
        },
        drawLine(from, to) {
            dispatch(drawLine(from, to));
        },
    };
}

export default connect(mapStateToProps, mapDispatchToProps)(PixelCanvas);
